{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0877264f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt \n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "cd6d5009",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>total_bill</th>\n",
       "      <th>tip</th>\n",
       "      <th>sex</th>\n",
       "      <th>smoker</th>\n",
       "      <th>day</th>\n",
       "      <th>time</th>\n",
       "      <th>size</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>16.99</td>\n",
       "      <td>1.01</td>\n",
       "      <td>Female</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10.34</td>\n",
       "      <td>1.66</td>\n",
       "      <td>Male</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>21.01</td>\n",
       "      <td>3.50</td>\n",
       "      <td>Male</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>23.68</td>\n",
       "      <td>3.31</td>\n",
       "      <td>Male</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>24.59</td>\n",
       "      <td>3.61</td>\n",
       "      <td>Female</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   total_bill   tip     sex smoker  day    time  size\n",
       "0       16.99  1.01  Female     No  Sun  Dinner     2\n",
       "1       10.34  1.66    Male     No  Sun  Dinner     3\n",
       "2       21.01  3.50    Male     No  Sun  Dinner     3\n",
       "3       23.68  3.31    Male     No  Sun  Dinner     2\n",
       "4       24.59  3.61  Female     No  Sun  Dinner     4"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data=sns.load_dataset(\"tips\")\n",
    "data=pd.DataFrame(data)\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "b6eef343",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "total_bill    0\n",
       "tip           0\n",
       "sex           0\n",
       "smoker        0\n",
       "day           0\n",
       "time          0\n",
       "size          0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "6737f435",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import LabelEncoder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "d040b257",
   "metadata": {},
   "outputs": [],
   "source": [
    "encoder=LabelEncoder()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c64742b6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\mdfir\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().\n",
      "  y = column_or_1d(y, warn=True)\n"
     ]
    }
   ],
   "source": [
    "data[\"sex\"]=encoder.fit_transform(data[[\"sex\"]])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53cc97e3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "e7b724b5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>total_bill</th>\n",
       "      <th>tip</th>\n",
       "      <th>sex</th>\n",
       "      <th>smoker</th>\n",
       "      <th>day</th>\n",
       "      <th>time</th>\n",
       "      <th>size</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>16.99</td>\n",
       "      <td>1.01</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10.34</td>\n",
       "      <td>1.66</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>21.01</td>\n",
       "      <td>3.50</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>23.68</td>\n",
       "      <td>3.31</td>\n",
       "      <td>1</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>24.59</td>\n",
       "      <td>3.61</td>\n",
       "      <td>0</td>\n",
       "      <td>No</td>\n",
       "      <td>Sun</td>\n",
       "      <td>Dinner</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   total_bill   tip  sex smoker  day    time  size\n",
       "0       16.99  1.01    0     No  Sun  Dinner     2\n",
       "1       10.34  1.66    1     No  Sun  Dinner     3\n",
       "2       21.01  3.50    1     No  Sun  Dinner     3\n",
       "3       23.68  3.31    1     No  Sun  Dinner     2\n",
       "4       24.59  3.61    0     No  Sun  Dinner     4"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "90627f3f",
   "metadata": {},
   "source": [
    "# check outliers "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "89decf82",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Axes: ylabel='total_bill'>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjMAAAGKCAYAAAD5f8DiAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAfZUlEQVR4nO3df0xd9f3H8dcF7QU6SoNfvRcUGnCgsZWKOrF0oWyOJnWrP7roZpnrjM5aqg6rqelAuRgK2sS2GiiO1rT4bWvTLVZt1hjYpr3Z2i6dpaHDpTqlLU1LmVKBanux3PP9wy93ZVB2uQLnfrjPR3Kj95zTy1tjvE/OT4dlWZYAAAAMFWX3AAAAAN8EMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaJfYPcBY8/v9OnHihOLj4+VwOOweBwAABMGyLPX09Cg5OVlRUcPve5nwMXPixAmlpKTYPQYAAAhBW1ubrrrqqmG3mfAxEx8fL+nrfxlTpkyxeRoAABCM7u5upaSkBL7HhzPhY6b/0NKUKVOIGQAADBPMKSKcAAwAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAw2oS/aR6Aiamvr0/Nzc3q7OxUYmKisrKyFB0dbfdYAGxAzAAwjtfr1bp169Te3h5Y5na7VVRUpLy8PBsnA2AHDjMBMIrX61VZWZnS09NVU1OjXbt2qaamRunp6SorK5PX67V7RADjzGFZlmX3EGOpu7tbCQkJ6urq4tlMgOH6+vpUWFio9PR0VVRUKCrq37+P+f1+lZaWqrW1VZs3b+aQE2C4kXx/s2cGgDGam5vV3t6uwsLCASEjSVFRUSosLNTJkyfV3Nxs04QA7EDMADBGZ2enJCktLW3I9f3L+7cDEBmIGQDGSExMlCS1trYOub5/ef92ACKDrTHj8XjkcDgGvNxud2C9ZVnyeDxKTk5WbGys8vPz1dLSYuPEAOyUlZUlt9utLVu2yO/3D1jn9/u1ZcsWJSUlKSsry6YJAdjB9j0z06dP18mTJwOvQ4cOBdatWrVKq1evVnV1tfbv3y+3262CggL19PTYODEAu0RHR6uoqEh79+5VaWmpWlpa9OWXX6qlpUWlpaXau3evlixZwsm/QISx9Womj8ejN998UwcPHhy0zrIsJScnq7i4WE8//bQkyefzyeVy6YUXXtDixYuD+hlczQRMPEPdZyYpKUlLlizhPjPABDGS72/bb5r30UcfKTk5WU6nUzk5OaqsrFR6erpaW1vV3t6uuXPnBrZ1Op2aM2eO9uzZc9GY8fl88vl8gffd3d1j/s8AYHzl5eVp9uzZ3AEYgCSbYyYnJ0evvfaaMjMzderUKVVUVCg3N1ctLS2B37hcLteAP+NyuXT06NGLfmZVVZXKy8vHdG4A9ouOjlZ2drbdYwAIA7aeMzNv3jz9+Mc/1vXXX68f/OAH+v3vfy9Jqq+vD2zjcDgG/BnLsgYtu9CKFSvU1dUVeLW1tY3N8AAAICzYfgLwhSZPnqzrr79eH330UeCqpguPiUtSR0fHoL01F3I6nZoyZcqAFwAAmLjCKmZ8Pp/+8Y9/KCkpSWlpaXK73WpsbAys7+3t1e7du5Wbm2vjlAAAIJzYes7MU089pfnz5ys1NVUdHR2qqKhQd3e3Fi1aJIfDoeLiYlVWViojI0MZGRmqrKxUXFycFi5caOfYAAAgjNgaM8ePH9d9992nTz/9VJdffrluvfVW7du3T9OmTZMkLV++XGfPnlVRUZFOnz6tnJwcNTQ0KD4+3s6xAQBAGOGp2QAAIOwYdZ8ZAAhFb2+v3nrrLZ04cULJycm68847NWnSJLvHAmADYgaAcV555RVt3759wPOZamtrde+99+qRRx6xcTIAdgirq5kA4L955ZVXtG3btiHXbdu2Ta+88so4TwTAbsQMAGP09vZq+/btkqRbbrlFNTU12rVrl2pqanTLLbdIkrZv367e3l47xwQwzogZAMbYsWOH/H6/rr76alVWVmr69OmKi4vT9OnTA8918/v92rFjh92jAhhHxAwAYxw6dEiS9NBDDykqauD/vqKiovTggw8O2A5AZCBmABgjNjZWknTy5Mkh1/c//qR/OwCRgZgBYIy5c+dKkjZu3Kjz588PWHf+/Hlt2rRpwHYAIgMxA8AYN954o+Li4tTT06N77rlHO3fu1KeffqqdO3fqnnvuUU9PjyZPnqwbb7zR7lEBjCPuAAzAKF6vV88+++xF1z/33HPKy8sbx4kAjIWRfH+zZwaAUfLy8vTcc8/J5XINWO52uwkZIEKxZwaAkfr6+tTc3KzOzk4lJiYqKytL0dHRdo8FYJTwbCYAE150dLSys7PtHgNAGOAwEwAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBo3DQPgJG4AzCAfsQMAON4vV6tW7dO7e3tgWVut1tFRUU8mwmIQBxmAmAUr9ersrIypaenq6amRrt27VJNTY3S09NVVlYmr9dr94gAxhkPmgRgjL6+PhUWFio9PV0VFRWKivr372N+v1+lpaVqbW3V5s2bOeQEGG4k39/smQFgjObmZrW3t6uwsHBAyEhSVFSUCgsLdfLkSTU3N9s0IQA7EDMAjNHZ2SlJSktLG3J9//L+7QBEBmIGgDESExMlSa2trUOu71/evx2AyEDMADBGVlaW3G63tmzZoq+++kpNTU364x//qKamJn311VfasmWLkpKSlJWVZfeoAMYRl2YDMEZ0dLSKiopUVlamH/3oR/L5fIF1TqdTvb29Ki8v5+RfIMKwZwaAcS52EeYEvzgTwEWwZwaAMfr6+rRu3Trl5uaqvLxcf//73wN3AJ4xY4bKyspUW1ur2bNns3cGiCDsmQFgjAsvzb700kuVnZ2t2267TdnZ2br00ku5NBuIUMQMAGNwaTaAoRAzAIzBpdkAhkLMADDGhZdm+/3+Aev8fj+XZgMRipgBYIz+S7P37t2r0tJStbS06Msvv1RLS4tKS0u1d+9eLVmyhJN/gQjDgyYBGMfr9aqmpkanTp0KLHO73SoqKlJeXp6NkwEYLTxoEsCE53A47B4BQJggZgAYxev1qqysTOnp6aqpqdGuXbtUU1Oj9PR0lZWVyev12j0igHHGYSYAxujr61NhYaHS09NVUVGhqKh//z7m9/tVWlqq1tZWbd68mfNmAMNxmAnAhHThTfMuDBlJioqK4qZ5QIQiZgAYg5vmARgKMQPAGNw0D8BQiBkAxuCmeQCGQswAMAY3zQMwFK5mAmAcr9erdevWqb29PbAsKSlJS5Ys4aZ5wAQxku9vYgaAkfr6+tTc3KzOzk4lJiYqKyuLPTLABDKS7+9LxmkmABhV0dHRys7OtnsMAGGAc2YAAIDR2DMDwEgcZgLQj5gBYJyhTgDmqdlA5OIwEwCj8KBJAP+Jq5kAGIMHTQKRgwdNApiQeNAkgKFwzgwAY1z4oMmhTgDmQZNAZCJmABij/wGSO3bs0M6dOwedADx//vwB2wGIDMQMAGNkZWVp6tSpWr9+vWbNmqVnnnlGaWlpgfNk1q9fr6lTp/KgSSDCcM4MgAnF4XDYPQKAcRY2MVNVVSWHw6Hi4uLAMsuy5PF4lJycrNjYWOXn56ulpcW+IQHYqrm5WZ9//rl++ctfqrW1VUuXLtXtt9+upUuX6siRI3rooYd0+vRpTgAGIkxYHGbav3+/6urqBu0aXrVqlVavXq1NmzYpMzNTFRUVKigo0OHDhxUfH2/TtADs0n9i7913362f/vSng04A9vl82rBhAycAAxHG9pg5c+aMCgsLtX79elVUVASWW5altWvXqqSkRAsWLJAk1dfXy+VyaevWrVq8eLFdIyPCnTt3TseOHbN7jIj05ZdfSvr6xnnp6emaPHmyJk+eLEn6+OOP9fHHHwe2+/DDD22bM5KlpqYqJibG7jEQYWy/ad6iRYuUmJioNWvWKD8/XzfccIPWrl2rTz75RFdffbUOHDgw4Mm4d955p6ZOnar6+vohP8/n88nn8wXed3d3KyUlhZvmYdR8+OGHevjhh+0eAwhLdXV1yszMtHsMTAAjuWmerXtmtm3bpgMHDmj//v2D1vVfculyuQYsd7lcOnr06EU/s6qqSuXl5aM7KHCB1NRU1dXV2T1GxDpw4IB+85vf6Prrr1d2drbq6+u1aNEiNTU16dChQ1q8eLFuvPFGu8eMWKmpqXaPgAhkW8y0tbXpV7/6lRoaGobdJfmfVyZYljXs1QorVqzQsmXLAu/798wAoyUmJobfPG2UmZmp5ORkrVu3LrCHtr6+XklJSSovL+dBk0AEsi1m3n//fXV0dOimm24KLOvr65PX61V1dbUOHz4s6es9NElJSYFtOjo6Bu2tuZDT6ZTT6Ry7wQHYLi8vT7Nnz9auXbv04osv6sknn9Ttt9/O85iACGXbpdm33XabDh06pIMHDwZeN998swoLC3Xw4EGlp6fL7XarsbEx8Gd6e3u1e/du5ebm2jU2gDARHR2ta665RpJ0zTXXEDJABLNtz0x8fLxmzJgxYNnkyZN12WWXBZYXFxersrJSGRkZysjIUGVlpeLi4rRw4UI7RgYAAGHI9kuzh7N8+XKdPXtWRUVFOn36tHJyctTQ0MA9ZgAAQEBYxcx777034L3D4ZDH45HH47FlHgAAEP7C5nEGAAAAoSBmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYLRLgt2wubk56A/NysoKaRgAAICRCjpmbrjhBjkcDlmWNeT6/nUOh0N9fX1BfWZtba1qa2t15MgRSdL06dP17LPPat68eZIky7JUXl6uuro6nT59Wjk5OaqpqdH06dODHRsAAExwQcdMa2vrqP/wq666Ss8//7y+/e1vS5Lq6+t15513qqmpSdOnT9eqVau0evVqbdq0SZmZmaqoqFBBQYEOHz6s+Pj4UZ8HAACYJ+iYmTZt2qj/8Pnz5w94v3LlStXW1mrfvn267rrrtHbtWpWUlGjBggWSvo4dl8ulrVu3avHixaM+DwAAME/QMfP2228H/aF33HHHiAfp6+vTb3/7W33xxReaNWuWWltb1d7errlz5wa2cTqdmjNnjvbs2XPRmPH5fPL5fIH33d3dI54FAACYI+iYueuuu4LabiTnzEjSoUOHNGvWLJ07d07f+ta3tGPHDl133XXas2ePJMnlcg3Y3uVy6ejRoxf9vKqqKpWXlwf98wEAgNmCvjTb7/cH9RpJyEjSNddco4MHD2rfvn1asmSJFi1apA8++CCw3uFwDNi+/yTji1mxYoW6uroCr7a2thHNAwAAzBL0npmxMmnSpMAJwDfffLP279+vl156SU8//bQkqb29XUlJSYHtOzo6Bu2tuZDT6ZTT6RzboQEAQNgIOmZefvllPfzww4qJidHLL7887LaPP/54yANZliWfz6e0tDS53W41NjYqOztbktTb26vdu3frhRdeCPnzAQDAxBJ0zKxZs0aFhYWKiYnRmjVrLrqdw+EIOmZ+/etfa968eUpJSVFPT4+2bdum9957T++8844cDoeKi4tVWVmpjIwMZWRkqLKyUnFxcVq4cGGwYwMAgAkupPvMjNY9Z06dOqX7779fJ0+eVEJCgrKysvTOO++ooKBAkrR8+XKdPXtWRUVFgZvmNTQ0cI8ZAAAQ8I3Pmem/I/BwJ+VezKuvvjrseofDIY/HI4/HE8poAAAgAoT8oMlXX31VM2bMUExMjGJiYjRjxgxt2LBhNGcDAAD4r0LaM/PMM89ozZo1euyxxzRr1ixJ0t69e/XEE0/oyJEjqqioGNUhAQAALiakmKmtrdX69et13333BZbdcccdysrK0mOPPUbMAACAcRPSYaa+vj7dfPPNg5bfdNNNOn/+/DceCgAAIFghxczPfvYz1dbWDlpeV1enwsLCbzwUAABAsII+zLRs2bLA3zscDm3YsEENDQ269dZbJUn79u1TW1ubfv7zn4/+lAAAABcRdMw0NTUNeH/TTTdJkj7++GNJ0uWXX67LL79cLS0tozgeAADA8IKOmXfffXfEH378+HElJycrKirkK8ABAACGNaaVcd111+nIkSNj+SMAAECEG9OY6b87MAAAwFjh+A8AADAaMQMAAIxGzAAAAKONacyE8iRtAACAkeAEYAAAYLSQHjQZrA8++EDJyclj+SMAAECECzpmFixYEPSHvvHGG5KklJSUkU8EAAAwAkHHTEJCwljOAQAAEJKgY2bjxo1jOQcAAEBIuDQbAAAYLeQTgH/3u99p+/btOnbsmHp7ewesO3DgwDceDAAAIBgh7Zl5+eWX9cADD+iKK65QU1OTbrnlFl122WX65JNPNG/evNGeEQAA4KJCipl169aprq5O1dXVmjRpkpYvX67GxkY9/vjj6urqGu0ZAQAALiqkmDl27Jhyc3MlSbGxserp6ZEk3X///Xr99ddHbzoAAID/IqSYcbvd+uyzzyRJ06ZN0759+yRJra2t3PUXAACMq5Bi5vvf/7527twpSXrwwQf1xBNPqKCgQD/5yU909913j+qAAAAAwwnpaqa6ujr5/X5J0iOPPKLExET9+c9/1vz58/XII4+M6oAAAADDCSlmjh8/PuBRBffee6/uvfdeWZaltrY2paamjtqAAAAAwwnpMFNaWpr+9a9/DVre2dmptLS0bzwUAABAsEKKGcuy5HA4Bi0/c+aMYmJivvFQAAAAwRrRYaZly5ZJkhwOh5555hnFxcUF1vX19emvf/2rbrjhhlEdEAAAYDgjipmmpiZJX++ZOXTokCZNmhRYN2nSJM2cOVNPPfXU6E4IAAAwjBHFzLvvvitJeuCBB/TSSy9pypQpYzIUAABAsEK6mmnjxo2Bvz9+/LgcDoeuvPLKURsKQzt16hSPiwAucPTo0QF/BfBvCQkJcrlcdo8xLhxWCLfs9fv9qqio0IsvvqgzZ85IkuLj4/Xkk0+qpKREUVEhnVc8Jrq7u5WQkKCuri6j9ySdOnVKP7v/5/qq12f3KAAAA1w6yanN//uasUEzku/vkPbMlJSU6NVXX9Xzzz+v2bNny7Is/eUvf5HH49G5c+e0cuXKkAbHxXV1demrXp/Ops+RPybB7nEAAGEs6lyX9MludXV1GRszIxFSzNTX12vDhg264447AstmzpypK6+8UkVFRcTMGPLHJMg/+X/sHgMAgLAR0vGgzs5OXXvttYOWX3vtters7PzGQwEAAAQrpJiZOXOmqqurBy2vrq7WzJkzv/FQAAAAwQrpMNOqVav0wx/+UH/4wx80a9YsORwO7dmzR21tbdq1a9dozwgAAHBRIT+b6cMPP9Tdd9+tzz//XJ2dnVqwYIEOHz6sadOmjfaMAAAAFxXSnpm0tDSdPHly0Im+n332mVJSUtTX1zcqwwEAAPw3IT9ocig8aBIAAIy3kB80+eyzz/KgSQAAYDseNAkAAIzGgyYBAIDRvvGDJgEAAOwUPk+EBAAACAExAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGi2xkxVVZW+853vKD4+XldccYXuuusuHT58eMA2lmXJ4/EoOTlZsbGxys/PV0tLi00TAwCAcGNrzOzevVtLly7Vvn371NjYqPPnz2vu3Ln64osvAtusWrVKq1evVnV1tfbv3y+3262CggL19PTYODkAAAgXl9j5w995550B7zdu3KgrrrhC77//vvLy8mRZltauXauSkhItWLBAklRfXy+Xy6WtW7dq8eLFdowNAADCSFidM9PV1SVJSkxMlCS1traqvb1dc+fODWzjdDo1Z84c7dmzZ8jP8Pl86u7uHvACAAATV9jEjGVZWrZsmb773e9qxowZkqT29nZJksvlGrCty+UKrPtPVVVVSkhICLxSUlLGdnAAAGCrsImZRx99VM3NzXr99dcHrXM4HAPeW5Y1aFm/FStWqKurK/Bqa2sbk3kBAEB4sPWcmX6PPfaY3n77bXm9Xl111VWB5W63W9LXe2iSkpICyzs6OgbtrenndDrldDrHdmAAABA2bN0zY1mWHn30Ub3xxhv605/+pLS0tAHr09LS5Ha71djYGFjW29ur3bt3Kzc3d7zHBQAAYcjWPTNLly7V1q1b9dZbbyk+Pj5wHkxCQoJiY2PlcDhUXFysyspKZWRkKCMjQ5WVlYqLi9PChQvtHB0AAIQJW2OmtrZWkpSfnz9g+caNG/WLX/xCkrR8+XKdPXtWRUVFOn36tHJyctTQ0KD4+PhxnhYAAIQjW2PGsqz/uo3D4ZDH45HH4xn7gQAAgHHC5momAACAUBAzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIwWFg+aRPCizn5u9wgAgDAXad8VxIxhYlu9do8AAEBYIWYMczYtT/7YqXaPAQAIY1FnP4+oX36JGcP4Y6fKP/l/7B4DAICwwQnAAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMdondA2Bkos512T0CACDMRdp3BTFjiISEBF06ySl9stvuUQAABrh0klMJCQl2jzEuiBlDuFwubf7f19TVFVm1DQzn6NGjWrlypUpKSjRt2jS7xwHCSkJCglwul91jjAtixiAulyti/sMERmLatGnKzMy0ewwANuEEYAAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNFtjxuv1av78+UpOTpbD4dCbb745YL1lWfJ4PEpOTlZsbKzy8/PV0tJiz7AAACAs2RozX3zxhWbOnKnq6uoh169atUqrV69WdXW19u/fL7fbrYKCAvX09IzzpAAAIFxdYucPnzdvnubNmzfkOsuytHbtWpWUlGjBggWSpPr6erlcLm3dulWLFy8ez1EBAECYCttzZlpbW9Xe3q65c+cGljmdTs2ZM0d79uy56J/z+Xzq7u4e8AIAABNX2MZMe3u7JMnlcg1Y7nK5AuuGUlVVpYSEhMArJSVlTOcEAAD2CtuY6edwOAa8tyxr0LILrVixQl1dXYFXW1vbWI8IAABsZOs5M8Nxu92Svt5Dk5SUFFje0dExaG/NhZxOp5xO55jPBwAAwkPY7plJS0uT2+1WY2NjYFlvb692796t3NxcGycDAADhxNY9M2fOnNE///nPwPvW1lYdPHhQiYmJSk1NVXFxsSorK5WRkaGMjAxVVlYqLi5OCxcutHFqAAAQTmyNmb/97W/63ve+F3i/bNkySdKiRYu0adMmLV++XGfPnlVRUZFOnz6tnJwcNTQ0KD4+3q6RAQBAmLE1ZvLz82VZ1kXXOxwOeTweeTye8RsKAAAYJWzPmQEAAAgGMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGjEDAAAMBoxAwAAjEbMAAAAoxEzAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKMRMwAAwGiX2D0AYJpz587p2LFjdo8BSUePHh3wV9gvNTVVMTExdo+BCEPMACN07NgxPfzww3aPgQusXLnS7hHw/+rq6pSZmWn3GIgwxAwwQqmpqaqrq7N7DCAspaam2j0CIhAxA4xQTEwMv3kCQBjhBGAAAGA0YgYAABiNmAEAAEYjZgAAgNGIGQAAYDRiBgAAGI2YAQAARiNmAACA0YgZAABgNGIGAAAYjZgBAABGI2YAAIDRiBkAAGC0Cf/UbMuyJEnd3d02TwIAAILV/73d/z0+nAkfMz09PZKklJQUmycBAAAj1dPTo4SEhGG3cVjBJI/B/H6/Tpw4ofj4eDkcDrvHATCKuru7lZKSora2Nk2ZMsXucQCMIsuy1NPTo+TkZEVFDX9WzISPGQATV3d3txISEtTV1UXMABGME4ABAIDRiBkAAGA0YgaAsZxOp8rKyuR0Ou0eBYCNOGcGAAAYjT0zAADAaMQMAAAwGjEDAACMRswAAACjETMAAMBoxAwAADAaMQMAAIxGzAAAAKP9H1saZKv1cMZnAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.boxplot(data[\"total_bill\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be90d87f",
   "metadata": {},
   "source": [
    "# remove outliers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "15aa7521",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# q_1=data[\"total_bill\"].quantile(.25)\n",
    "# q_2=data[\"total_bill\"].quantile(.50)\n",
    "# q_3=data[\"total_bill\"].quantile(.75)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "a76038ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "# IQR=q_3-q_1\n",
    "# IQR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "979c502a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# min_range=q_1-(1.5*IQR)\n",
    "# mix_range=q_3+(1.5*IQR)\n",
    "# (min_range,mix_range)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "8c830f02",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# a=data[data[\"total_bill\"] <= mix_range]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "043d5574",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# q_1=data[\"tip\"].quantile(.25)\n",
    "# q_2=data[\"tip\"].quantile(.50)\n",
    "# q_3=data[\"tip\"].quantile(.75)\n",
    "# IQR=q_3-q_1\n",
    "# min_range=q_1-(1.5*IQR)\n",
    "# mix_range=q_3+(1.5*IQR)\n",
    "# data=data[data[\"tip\"] <= mix_range]\n",
    "\n",
    "\n",
    "\n",
    "# sns.boxplot(data[\"tip\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "73730085",
   "metadata": {},
   "source": [
    "# linear regression and train_test_split use "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "8e0d53f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn .model_selection import train_test_split\n",
    "from sklearn .linear_model import LinearRegression"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "86a06f00",
   "metadata": {},
   "outputs": [],
   "source": [
    "x=data[[\"total_bill\"]]\n",
    "y=data[\"tip\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "4cdc78d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "53141079",
   "metadata": {},
   "outputs": [],
   "source": [
    "lr=LinearRegression()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "8cd8084f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  display: none;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  overflow: visible;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".estimator-table summary {\n",
       "    padding: .5rem;\n",
       "    font-family: monospace;\n",
       "    cursor: pointer;\n",
       "}\n",
       "\n",
       ".estimator-table details[open] {\n",
       "    padding-left: 0.1rem;\n",
       "    padding-right: 0.1rem;\n",
       "    padding-bottom: 0.3rem;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table {\n",
       "    margin-left: auto !important;\n",
       "    margin-right: auto !important;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(odd) {\n",
       "    background-color: #fff;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(even) {\n",
       "    background-color: #f6f6f6;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:hover {\n",
       "    background-color: #e0e0e0;\n",
       "}\n",
       "\n",
       ".estimator-table table td {\n",
       "    border: 1px solid rgba(106, 105, 104, 0.232);\n",
       "}\n",
       "\n",
       ".user-set td {\n",
       "    color:rgb(255, 94, 0);\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td.value pre {\n",
       "    color:rgb(255, 94, 0) !important;\n",
       "    background-color: transparent !important;\n",
       "}\n",
       "\n",
       ".default td {\n",
       "    color: black;\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td i,\n",
       ".default td i {\n",
       "    color: black;\n",
       "}\n",
       "\n",
       ".copy-paste-icon {\n",
       "    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n",
       "    background-repeat: no-repeat;\n",
       "    background-size: 14px 14px;\n",
       "    background-position: 0;\n",
       "    display: inline-block;\n",
       "    width: 14px;\n",
       "    height: 14px;\n",
       "    cursor: pointer;\n",
       "}\n",
       "</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LinearRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n",
       "        <div class=\"estimator-table\">\n",
       "            <details>\n",
       "                <summary>Parameters</summary>\n",
       "                <table class=\"parameters-table\">\n",
       "                  <tbody>\n",
       "                    \n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('fit_intercept',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">fit_intercept&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('copy_X',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">copy_X&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('tol',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">tol&nbsp;</td>\n",
       "            <td class=\"value\">1e-06</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('n_jobs',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">n_jobs&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('positive',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">positive&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "                  </tbody>\n",
       "                </table>\n",
       "            </details>\n",
       "        </div>\n",
       "    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n",
       "    // Get the parameter prefix from the closest toggleable content\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n",
       "\n",
       "    const originalStyle = element.style;\n",
       "    const computedStyle = window.getComputedStyle(element);\n",
       "    const originalWidth = computedStyle.width;\n",
       "    const originalHTML = element.innerHTML.replace('Copied!', '');\n",
       "\n",
       "    navigator.clipboard.writeText(fullParamName)\n",
       "        .then(() => {\n",
       "            element.style.width = originalWidth;\n",
       "            element.style.color = 'green';\n",
       "            element.innerHTML = \"Copied!\";\n",
       "\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        })\n",
       "        .catch(err => {\n",
       "            console.error('Failed to copy:', err);\n",
       "            element.style.color = 'red';\n",
       "            element.innerHTML = \"Failed!\";\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        });\n",
       "    return false;\n",
       "}\n",
       "\n",
       "document.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n",
       "\n",
       "    element.setAttribute('title', fullParamName);\n",
       "});\n",
       "</script></body>"
      ],
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lr.fit(x_train,y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "6f79c19b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(244, 7)"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "ec385f18",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>total_bill</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>228</th>\n",
       "      <td>13.28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>208</th>\n",
       "      <td>24.27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96</th>\n",
       "      <td>27.28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>167</th>\n",
       "      <td>31.71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84</th>\n",
       "      <td>15.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>106</th>\n",
       "      <td>20.49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>14.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>92</th>\n",
       "      <td>5.75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>179</th>\n",
       "      <td>34.63</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>102</th>\n",
       "      <td>44.30</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>195 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     total_bill\n",
       "228       13.28\n",
       "208       24.27\n",
       "96        27.28\n",
       "167       31.71\n",
       "84        15.98\n",
       "..          ...\n",
       "106       20.49\n",
       "14        14.83\n",
       "92         5.75\n",
       "179       34.63\n",
       "102       44.30\n",
       "\n",
       "[195 rows x 1 columns]"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "4b9c7b1a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "228    2.72\n",
       "208    2.03\n",
       "96     4.00\n",
       "167    4.50\n",
       "84     2.03\n",
       "       ... \n",
       "106    4.06\n",
       "14     3.02\n",
       "92     1.00\n",
       "179    3.55\n",
       "102    2.50\n",
       "Name: tip, Length: 195, dtype: float64"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "ce9868e5",
   "metadata": {},
   "outputs": [],
   "source": [
    "y_pred=lr.predict(x_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "ccf4dc5e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([3.04525623, 1.86330727, 3.55119456, 3.69452593, 2.31576375,\n",
       "       2.83881627, 3.96728338, 2.26014262, 2.50615915, 2.57033737,\n",
       "       2.88160176, 2.07723468, 2.06439904, 2.47407003, 2.00236009,\n",
       "       2.91903905, 2.92652651, 3.23351235, 2.68478854, 5.33107064,\n",
       "       3.13831465, 3.13403611, 2.4558862 , 1.94673896, 3.16077703,\n",
       "       2.17564129, 2.02375283, 3.62927807, 2.68906708, 6.07767732,\n",
       "       4.99734388, 1.75313465, 2.83025918, 3.09552917, 2.74040966,\n",
       "       3.50092162, 2.21200895, 5.53644096, 2.33287794, 3.35010279,\n",
       "       2.04942412, 2.47834858, 3.48701634, 2.03017065, 2.03124029,\n",
       "       1.25361414, 2.05798121, 2.92438724, 1.73388118])"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_pred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "633abcaa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.10696371])"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lr.coef_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "0e50d084",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.9252355585570555"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lr.intercept_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "3a003eeb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x1d8400512e0>]"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAh8AAAGdCAYAAACyzRGfAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAABKdUlEQVR4nO3de3wU1d0/8M9u7sRkIVDYRBAi4iUEQVDuVougUUCsfWxFsVb78LQULGr7E7H1AeolUFu8FB9QW68UqG1BwUsURUE0FDREiJEqIQiFxEgCSQgkwO78/lgnbDY71509s7P7eb9eeb1gc3bO2dnNznfO5XtckiRJICIiIhLEbXcDiIiIKLEw+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISisEHERERCcXgg4iIiIRKtrsBofx+Pw4ePIisrCy4XC67m0NEREQ6SJKE5uZm5OXlwe1W79uIueDj4MGD6NOnj93NICIiIhP279+P3r17q5aJueAjKysLQKDx2dnZNreGiIiI9GhqakKfPn3ar+NqYi74kIdasrOzGXwQERE5jJ4pE5xwSkREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISisEHERERCcXgg4iIiISKuSRjREREFB0+v4St1Q2oa25Fz6x0DM/PQZJb/D5qhns+Nm3ahMmTJyMvLw8ulwuvvPJKh99LkoT58+cjLy8PGRkZuPzyy/HZZ59Z1V4iIiIyoaSiBmMXbcDUZ7Zg9qpyTH1mC8Yu2oCSihrhbTEcfLS0tGDw4MFYsmRJ2N///ve/x+LFi7FkyRJs27YNXq8XEyZMQHNzc8SNJSIiIuNKKmowY3kZahpbOzxe29iKGcvLhAcgLkmSJNNPdrmwZs0aXHfddQACvR55eXm48847MWfOHABAW1sbevXqhUWLFuFnP/uZ5jGbmprg8XjQ2NjIvV2IiIgi5PNLGLtoQ6fAQ+YC4PWkY/OccRENwRi5fls64bS6uhq1tbW48sor2x9LS0vDZZddho8++ijsc9ra2tDU1NThh4iIiKyxtbpBMfAAAAlATWMrtlY3CGuTpcFHbW0tAKBXr14dHu/Vq1f770IVFxfD4/G0//Tp08fKJhERESW0umblwMNMOStEZalt6Ha6kiQpbrE7d+5cNDY2tv/s378/Gk0iIiJKSD2z0i0tZwVLl9p6vV4AgR6Q3Nzc9sfr6uo69YbI0tLSkJaWZmUziIiI6FvD83OQ60lHbWMrwk3ylOd8DM/PEdYmS3s+8vPz4fV6sX79+vbHTpw4gY0bN2L06NFWVkVEREQ6JLldmDe5AEAg0Agm/3/e5AKh+T4MBx9Hjx5FeXk5ysvLAQQmmZaXl2Pfvn1wuVy488478fDDD2PNmjWoqKjAT37yE3Tp0gU33XST1W0nIiIiHYoKc7F02lB4PR2HVryedCydNhRFhbkKz4wOw0tt33//fXzve9/r9Pitt96K559/HpIkYcGCBXjqqadw+PBhjBgxAk8++SQKCwt1HZ9LbYmIiKIjmhlOjVy/I8rzEQ0MPoiIiJzHtjwfRERERFoYfBAREZFQDD6IiIhIKAYfREREJBSDDyIiIhKKwQcREREJxeCDiIiIhGLwQUREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISisEHERERCcXgg4iIiIRi8EFERERCMfggIiIioRh8EBERkVAMPoiIiEgoBh9EREQkFIMPIiIiEorBBxEREQnF4IOIiIiEYvBBREREQjH4ICIiIqEYfBAREZFQyXY3gIiIiE7z+SVsrW5AXXMremalY3h+DpLcLrubZSkGH0RERDGipKIGC9ZVoqaxtf2xXE865k0uQFFhro0tsxaHXYiIiGJASUUNZiwv6xB4AEBtYytmLC9DSUWNTS2zHoMPIiIim/n8Ehasq4QU5nfyYwvWVcLnD1fCeRh8EBER2WxrdUOnHo9gEoCaxlZsrW4Q16goYvBBRERks7pm5cDDTLlYx+CDiIjIZj2z0i0tF+sYfBAREdlseH4Ocj3pUFpQ60Jg1cvw/ByRzYoaBh9EREQ2S3K7MG9yAQB0CkDk/8+bXBA3+T4YfBAREcWAosJcLJ02FF5Px6EVrycdS6cNjas8H0wyRkREFCOKCnMxocDLDKdEREQkTpLbhVH9u9vdjKjisAsREREJxeCDiIiIhGLwQUREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISisEHERERCcXgg4iIiIRi8EFERERCMfggIiIioRh8EBERkVAMPoiIiEgoBh9EREQkFIMPIiIiEorBBxEREQnF4IOIiIiEYvBBREREQjH4ICIiIqEYfBAREZFQDD6IiIhIKAYfREREJBSDDyIiIhKKwQcREREJxeCDiIiIhLI8+Dh16hR++9vfIj8/HxkZGTj77LPxu9/9Dn6/3+qqiIiIyIGSrT7gokWLsGzZMrzwwgsYOHAgPv74Y9x2223weDyYPXu21dURERGRw1gefJSWlmLKlCmYOHEiAKBfv35YuXIlPv74Y6urIiIiIgeyfNhl7NixePfdd/HFF18AAD799FNs3rwZ11xzTdjybW1taGpq6vBDRERE8cvyno85c+agsbER559/PpKSkuDz+fDQQw9h6tSpYcsXFxdjwYIFVjeDiIiIYpTlPR9/+9vfsHz5cqxYsQJlZWV44YUX8Ic//AEvvPBC2PJz585FY2Nj+8/+/futbhIRERHFEJckSZKVB+zTpw/uvfdezJw5s/2xBx98EMuXL8euXbs0n9/U1ASPx4PGxkZkZ2db2TQiIiKKEiPXb8t7Po4dOwa3u+Nhk5KSuNSWiIiIAERhzsfkyZPx0EMP4ayzzsLAgQOxfft2LF68GLfffrvVVREREZEDWT7s0tzcjPvvvx9r1qxBXV0d8vLyMHXqVPzv//4vUlNTNZ/PYRciIiLnMXL9tjz4iBSDDyIiIuexdc4HERERkRoGH0RERCQUgw8iIiISisEHERERCWX5UlsiIkocPr+ErdUNqGtuRc+sdAzPz0GS22V3syjGMfggIiJTSipqsGBdJWoaW9sfy/WkY97kAhQV5trYMop1HHYhIiLDSipqMGN5WYfAAwBqG1sxY3kZSipqbGoZOQGDDyIiMsTnl7BgXSXCJYmSH1uwrhI+f0ylkaIYwuCDiIgM2Vrd0KnHI5gEoKaxFVurG8Q1ihyFwQcRERlS16wceJgpR4mHwQcRERnSMyvd0nKUeBh8EBGRIcPzc5DrSYfSgloXAqtehufniGwWOQiDDyIiMiTJ7cK8yQUA0CkAkf8/b3IB832QIgYfRERkWFFhLpZOGwqvp+PQiteTjqXThjLPB6likjEiIjKlqDAXEwq8zHBKhjH4ICIi05LcLozq393uZpDDcNiFiIiIhGLwQUREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISisEHERERCcXgg4iIiIRi8EFERERCMfggIiIioRh8EBERkVAMPoiIiEgoBh9EREQkFIMPIiIiEorBBxEREQnF4IOIiIiEYvBBREREQjH4ICIiIqEYfBAREZFQyXY3gIiIiAJ8fglbqxtQ19yKnlnpGJ6fgyS3y+5mWY7BBxGRjRLlYkPaSipqsGBdJWoaW9sfy/WkY97kAhQV5trYMusx+CAiskkiXWxIXUlFDWYsL4MU8nhtYytmLC/D0mlD4+ozwTkfREQ2kC82wYEHcPpiU1JRY1PLSDSfX8KCdZWdAg8A7Y8tWFcJnz9cCWdi8EFEJFgiXmxI2dbqhk5BaDAJQE1jK7ZWN4hrVJQx+CAiEiwRLzakrK5Z+bNgppwTMPggIhIsES82pKxnVrql5ZyAwQcRkWCJeLEhZcPzc5DrSYfSGicXAhORh+fniGxWVDH4IIpjPr+E0qp6vFp+AKVV9Y6aQ+DktmtJxIsNKUtyuzBvcgEAdPpMyP+fN7kgrpZgc6ktUZxy8jJOJ7ddD/liM2N5GVxAh4mn8XqxIXVFhblYOm1op8+9N44+98FckiTF1O1EU1MTPB4PGhsbkZ2dbXdziBxJKWeAfCmL5ZwBTm67UfEeZJFxTk46Z+T6zeCDKM74/BLGLtqguJrChcDd1OY542LuS83JbTfLyRcbomBGrt8cdiGKM0aWcY7q311cw3RwctvNSnK74ua1EOnFCadEccbJyzid3HYi0o/BB1GccfIyTie3nYj0Y/BBFGecvIzTyW0nIv0YfBDFGSfnDHBy24lIPwYfRHFIzhng9XQcnvB60mN+qaqT205E+nCpLVEcc/IyTie3nSgRcaktEQFw9jJOJ7ediNRx2IWIiIiEYvBBREREQjH4ICIiIqEYfBAREZFQDD6IiIhIKAYfREREJBSDDyIiIhKKeT6IiExgEjSy3KFDwFNPASNGAOPH292aqIpK8HHgwAHMmTMHb775Jo4fP45zzz0Xf/nLXzBs2LBoVEdEJFRJRQ0WrKtETWNr+2O5nnTMm1zA9O9k3DvvABMmdHzsX/8Chg+3pz0CWD7scvjwYYwZMwYpKSl48803UVlZiT/+8Y/o2rWr1VUREQlXUlGDGcvLOgQeAFDb2IoZy8tQUlFjU8vIUXw+4O67AZerc+ABAFlZ4tskkOU9H4sWLUKfPn3w3HPPtT/Wr18/q6shogRnx7CHzy9hwbpKhNsQS0Jg590F6yoxocDLIRgKb/9+4PLLgT17lMu8/DJwwQXCmmQHy4OPtWvX4qqrrsINN9yAjRs34swzz8QvfvELTJ8+PWz5trY2tLW1tf+/qanJ6iYRUZyxa9hja3VDpx6PYBKAmsZWbK1u4L401NHf/w788IfKv/d4gNLSuA86ZJYPu+zZswdLly7FgAED8NZbb+HnP/85fvnLX+LFF18MW764uBgej6f9p0+fPlY3iYgM8vkllFbV49XyAyitqofPHzubX9s57FHXrBx4mClHca6tDfjxjwNDK0qBxy23AK2twJEjCRN4AIBLkiRLv1VSU1Nx8cUX46OPPmp/7Je//CW2bduG0tLSTuXD9Xz06dNH15a8RGS9WJ5M6fNLGLtog2LvgwuA15OOzXPGRWXYo7SqHlOf2aJZbuX0kez5SGSVlcDIkUBzs3KZl18GbrhBXJsEaGpqgsfj0XX9trznIzc3FwUFBR0eu+CCC7Bv376w5dPS0pCdnd3hh4jsEeuTKY0Me0TD8Pwc5HrSoRTWuBAI1Ibn50Slfopxy5YFejkGDgwfePTvD3z1FSBJcRd4GGV58DFmzBj8+9//7vDYF198gb59+1pdFRFZSGsyJRCYTGnnEIzdwx5JbhfmTQ7cXIUGIPL/500u4GTTRNLUBBQVBYKOGTPCl7n7buDUKWD3buCss8S2L0ZZHnzcdddd2LJlCx5++GHs3r0bK1aswNNPP42ZM2daXRURWcjuXgU9emalW1rOjKLCXCydNhReT8c6vJ50LJ021PahKRLkX/8KBBweD/DWW+HLrF8f6OX44x+BpCSx7Ytxlq92ueSSS7BmzRrMnTsXv/vd75Cfn4/HHnsMN998s9VVEZGF7O5V0EMe9qhtbA3bQyPP+Yj2sEdRYS4mFHiZ4TTRSBLwwAPAvHnKZUaMAF57DejRQ1y7HCgqGU4nTZqESZMmRePQRBQlsdCroEUe9pixvAwuoEMAInrYI8nt4qTSRPHNN8DVVwOffKJcprgYmDMn0BtCmrixHBEBcM5kSg57kDBvvRUIJnr2VA48tm4N9Ijcey8DDwO4sRxRnNObCTSWehW0cNiDoubUqcAE0T/9SbnM5MnAihXAGWeIa1ecsTzPR6SMrBMmInVmcnbEcp4PoqjZuxe47DJAIS0EAODppwGFbN1k7PrN4IMoTsk5O0L/wOW+AbUhinjdLj5eXxdFYOVK4KablH+fkwN89BFw3nni2uRQRq7fHHYhikORboAWj5Mp2aND7VpbgdtvDwQeSm67LZA0LDVVXLsSCCecEsUhJ+TsECnWM7eSIBUVQJcuQEaGcuCxenVgAumzzzLwiCIGH0RxyAk5O0RxQuZWirIlSwIrUQYNAo4f7/z7884LbHUvScD3vy++fQmIwQdRHHJCzg5R2AuUoBobgQkTAkHHHXeEL3PPPYDPB+zaBfTuLbZ9CY5zPojiUKxkAo0F7AVKMFoTSAFgwwbge98T0x4Kiz0fRHGIG6Cdxl6gBOD3B3o4XC7lwGPMGKC+PjC0wsDDdgw+iOIUM4EGOCVzK5mwY0cg4FDbtO2RRwLByebNgWWzFBM47EIUx5gJ1FmZW0mnX/5SPQMpAGzbBlx8sZj2kGFMMkZECYF5PhyutTWwRFbL118H9mIh4ZhkjIgoBHuBHGrDBuCKK9TLjB0LfPCBmPaQJRh8EFHCiMfMrXHr6quBkhL1Mm+8EShHjsPgg4iIYkNDA9BdR3B49CiQmRn99lDUcLULERHZ6557AqtW1AKP224LLJOVJAYecYA9H0REJJ4kAW4d979ctRKXGHwQEcUYn1+K34mxn34KDBmiXe7kSSCZl6h4xXeWiCIW1xdLwUoqajB/7WeobWprf8ybnYb51w509pLgSZOA119XL3PVVdqTTCkuMPiIAfziJieL1fwZTvy7Kqmowc+Xl3V6vLapDT9fXoZlTstMe/Kkvm3py8qAiy6KfnsoZjDJmM1i9YubSI+SihrMWF7WafM6+RJvVxp3J/5d+fwShj24HkeOnVQs07VLCj757YSYD6LwxhvAxIna5eQ9WSguGLl+c7WLjeQv7tDtvmsbWzFjeRlKKmpsahmRNp9fwoJ1lWF3zZUfW7CuEj6/2Psbp/5dbamqVw08AODIsZPYUlUvqEUm5OYGggm1wONXvzq9aoWBR8Ji8GGTWP3iJtJra3VDpwt8MAlATWMrtlY3CGuTk/+uSvccsrScME1Np3eUra1VLrd/fyDg+MMfxLWNYhaDD5vE4hc3kRF1zcqfXzPlrODsvyu9vQAx0lvw5JOBgMPjUS8n93L07i2mXeQInHBqk1j84ibxIpkUaceEyuA6DzW3aT8BQM+sdMVjWN1uvX8v71TWhk2zbrZtVrymUf27Y8l7uzXLeTJS4PNL9s370DNUsmwZ8LOf6T6kVZ8JJ04yDub09hvB4MMmoV/IkZYj54lkUqQdEyrD1el2AUojGC4AXk/gC1RUu/X+vawpP4D7JhZ0+GI32zarXtPIs7uja5cUzXkfD73xOZ79sFrs5Nl9+4C+fbXLNTUBWVmGDm3V+XPiJONgTm+/URx2scnw/BzketIVO1BdCHzwgr+4KX5EMinSjgmVSnWqBR4AMG/y6Qu8iHYPz89BTqb20s6GlpMdhl7Mts3K15TkdmHh9YN0lRU2eXb27EBPh1rgcdZZp4dWTAQeVpw/p04yljm9/WYw+LBJktuFeZMLAHQewQ33xU3xI5JJkXZMqFSrUxb6MfV60jsssxXV7iS3C9cNydNVVh6iMdu2aLymosJcLJs2FN5s9R6cqE6elVehuFzAE08olyspCZT96itT1Vh1/pw8yRhwfvvNYvBho6LCXCydNhReT8cvmtAvboovkUyKtGNCpVadQKAH5P6JF+DxG4dg5fSR2DxnXIfPr8h2Tyjw6ionD9GYbVu0XlNRYS4+vHcc7p94gWo5y9/rjz8OBBxa+62cPBkIOq66KqLqrDp/zp5k7Pz2m8U5HzYrKszFhAJvwkwyosgmG9sxUVnvsXpkpWHKkDMjOoYV7ZaHNJW+0EPnophtWzRfU5LbhR5ZaVE7fgdXXAFs2KBeZsoU4JVXIqsnhFXnz+mT953efrMYfMSAJLcr7Mx7ik+RTDa2Y6KyFXWKbLc8pDnj2zTlwZ3V4YY0zbYt2q8pqsc/cQJI0xHc7NgBDNI3D8Uoq16f0yfvO739ZnHYhUiwSCYb2zFR2Yo6RbfbyJCm2bZF+zVF5fivvBIYWtEKPPz+wNBKlAIPwLrX5/TJ+05vv1kMPogEi2SysR0Tla2o0452FxXmYvOccVg5faTiXJRI2hbt12Tp8bt2DQQd3/++cpn77hOa9tyq1+f0yftOb79Z3FiOyCbxkOfDaJ2xnMvA7jwflh//8GEgR8fd8sGDgT1ZbMI8HwFObz9g7PrN4IPIRk7OcGq2zljO4mhnhlPLjv/oo8Ddd2sfVMBXv952M8NpgNPbz+CDiKLC6V+OcU3PUMmzzwK33Rb9tiA+7uTJGCPXb652ISJdeDGJLT6/hE83bcfQ7w3TLnz0KJCZGf1GfUvO2Bl6Zytn7GQeI+KEUyLSlIjpn2PZ/htuQVKSWz3wOO+80xNIBQYeiZqxk4xh8EFEqngxiRFBac/7/GO5YrGtf345UHbXLoGNC6o/QTN2kjEcdiEiVUYuJkyWFwWlpcDo0ZrFzv5/r0JyJ8Fbl47Nfsm2uTiJmrGTjGHwQUSqeDGxyejRgcBDxbrzL8UdU+Z0eMzuQDBRM3aSMQw+iEgVLyYCtbUB6drn8YqfLkVVjz6Kv7czEJQzdtY2toYdqgvdW4cSE+d8EJGqRE3/LNTf/x6Yz6EReJTuPoR+c15TDTwAewPBRM3YScYw+CAiVYl+MfH5JZRW1ePV8gMoraq3dmJtamog6PjhD5XLzJ/fvmrFKYGgkb11KDExyRgR6ZKIeT6i8prr64EePbTLff010LNn2Dap7dgbSxd3JqVLLMxwSkRRkUgXE6VEWaYv8gsXAnPnapfT8ZWciIEgxT4GH0REEfD5JYxdtEFxibE8aXLznHHawZeetOfLlwM332y4jYkSCJIzML06EVEEIs5t8uWXwLnnald07BiQkWGqjUluF/OqkGNxwikRUQjTuU1uvTXQ06EWeFx00em05yYDDyKnY88HERkW713+hnKb+P1AUpJ24U2bgEsvjbBlRPGBwQfFrXi6QMbSa0mEyY56EmVd1fAlRp0zSftgPh/gZiczUTBOOKW4FE8XyFh5LT6/hCUbvsSj73zZ6XexuMwzUkpLWt947g4U1FWrP/nWW4Hnn49a24hiEVe7UEKzfImkjWLltZRU1GD+2krUNinPhTC0AsQh5MCv4VAj/r34B9pP+OILYMCA6DeMKAYZuX6zL5DiSjxt/x4rr0UOgNQCD7lN8bZVelH5uyi9b7x24CFPIGXgQaQLgw+KK0aWSIoQSWruWHgtagGQkljY3TbilOguV+DnlluUyxQXnw46iMgQTjiluBJL279HOlcjFl6LVgAUjt2725o+73V1QK9e2hUcOgR0Z34Nokiw54PiSqxs/y4PVYReuGsbWzFjeRlKKmo0jxELr8VIYBMLm5qZOu8LFgR6OdQCj5SU070cDDyIIsbgg+JKLOz6adVcjVh4LUYDGzt3tzV83uWhlfnzlQ/68suBgOPECYtbS5TYGHxQXLFq+3c75mqE1im3NdLXEgmtAEjmzU6zfRWRnvOeWfUFkpLc2vuttLYGgo4bbrC2kUQEgHM+KA4VFeZi6bShncb9vTrnW4iaq1Hb1IrSqnrUNbdi76EWrNy6D7VNbZ3qjOS1REoO5mYsL4MLCNurcNf4czFr3Dm2L69VO+9LXl2ESbs+UD/A6NHAhx9a3CoiCod5PihumckKakVejdKqekx9Zotm+3IyU9DQclLx98F1Tijw2prhNFYSnakJPe9uvw97Hpmi44mlwMiRUWwZUWJgkjFqF0tpufWIVnvl49Y2taLhaBtyMlPh9WR0OL7WNuoA0DUjBU/ePBSX9MvBJ18dDttO+ThKqbmNiCRxl9XnMtzxAJiqw+eXsKWqHqV7DgEI7M468uzuEbdv7KINOPvTLfjr336r/QS/X9929wnGad8ZFDtiKvgoLi7Gfffdh9mzZ+Oxxx7TLM/gwzpOuFsNFq32hjtuuOPr7bEAALcLCJ4GEtpOpdTcSkMXWlZOH2lo+3QR773ZOkoqanDv6p04cqxjr0/XLilYeP0g8+0777xAhlEV+264BWe9/KK54ycAp31nUGyJmQyn27Ztw9NPP40LL7wwmtVQGFYs9RQpWu1VOq6sJuj4RpaVhs4/DW2nPO/E6+m4WiQnM9XYC/iWkbaJeO/N1lFSUYOfLy/rFHgAwJFjJ/Fzo+1raTm9akUl8PjBr19Eyc6DDDxUOO07g5wtasHH0aNHcfPNN+OZZ55Bt27dolUNhRErabn1ilZ79WbnlL49fo/MNEPHDz0G0LGdRYW52DxnHFZOH4nHbxyCldNH4r6rzzd1/EPNbbpW3oh4783W4fNLmL/2M83j62rfc88FAo4zzlAt9ur2/6B09yG8vGga79xVOO07g5wvasHHzJkzMXHiRIwfP161XFtbG5qamjr8UGRiIS23EdFqr5HsnDWNrYALupaVKgnXziR3YD7DlCFnYlT/7jhyXHmCqRK3C3jg9c8xe1U5pj6zBWMXbVC8CxXx3putIzDnpi38k4Kotk/u5bj9duUDPPpoe0Iw+bxzzoI6p31nkPNFJfhYtWoVysrKUFxcrFm2uLgYHo+n/adPnz7RaFJCiYW03EZEq71Gyx862qaYV8OqenPOMN67ojXEo7duM+UieW5oOSN1dii7Z8/poENNQ0Mg6LjzTt31UIDTvjPI+SwPPvbv34/Zs2dj+fLlSE/Xzo44d+5cNDY2tv/s37/f6iYlnFhIy21EtNprprzSXA2r6vVm6z+u0s26Wje4iPfebB1G6uyZlQ5ce20g4OjfX7lg166n055zeNc0p31nkPNZHnx88sknqKurw7Bhw5CcnIzk5GRs3LgRTzzxBJKTk+Hz+TqUT0tLQ3Z2docfikwspOU2Ilrt1ZudEyHHl+dq/PWnI9A1I0V3fXraKbdJTdcuKfjNNed36vEIptQNLuK9N1vH8PwceLM1en4kCXsXTcKoc3oA69Ypl3vllUDAcfiwkaaTAqd9Z5DzWR58XHHFFdi5cyfKy8vbfy6++GLcfPPNKC8vR1JSktVVUgirUoyLEq32Bh9XjSvM8ZPcLowZ0AMLfzAIrjDtCncMPe2U2xTumPJjC68fhJ46e0hCu8FFvPdm60hyuzD/2oFhj3nxfz7D3kWTsPf3k9Url9OeT9GRPIx0c9p3Bjmf5cFHVlYWCgsLO/xkZmaie/fuKCwstLo6UqA0fOD1pNu+B0c40WqvfFyl3oZcjeMXFebiyZsuQtcuHXtAQr+DjbRTz2uNpBtcxHtvto6iwlwsmza0/XyWPXET9i6ahH/8dY5yZcE7yqaZX5FE6pz2nUHOJiTD6eWXX44hQ4YwyZgNnJat0M4Mp+EoJcTypCfh9rFno1+PTNPtVHutWllS9WQ+tepcarXTcB0nTwKpOvKdrF8PaKyWI+s57TuDYkdMZTg1isEHWSXSL1E5IZaaZVG8I1TLkgro22fGijZYlvHy+eeB227TLse050SOxOCDEl6kF02fX8KYhRtQ26S+tNCbnYYP770ianeGdqa7tmKTvcATdJybyy8H3nvPYAvjD3sdyMmMXL+TBbWJSBili6acH0PPRVMeotFS29SGrdUNhvZdMaKoMNeWHW21Ml66EFjqO6HAG74tDQ1Adx3nZNeuwJ4sxH1VKKFEdW8XItGsShNtOiFWFIRmSRVxJ2w64+U99wR6OrQCD3kCKQMPANxXhRIPgw+KK1aliTacEMuhfH4JpVX1HfaN8fklfLj7kK7ntwdecgbSRx5RLnz33aeDDmrHfVUoEXHYheKKVWmiAwmx0nXN+XBq4qVw3fzyEthwu86GuqBuD6ZcNEm7ovp6IMeZ50gEIwFztIb3iERj8EFxxao00YGEWAWaq13mXzvQkRMClebF6Ak6yp64CTnHdWwAyR4OXbivCiUiDrtQXLEyTXRoQqxgXbukRHWZbTSpdfMr+jbt+d5Fk9QDjz/9iUMrBnFfFUpE7PmguCKniZ6xvAwuhM+Pcf/ECzqsHhnWtxu2VTegdM8hAIHJnSPPDkzsnFDgRVZ6Cj6qOoQDh48jr2s6xvT/DkaqTPw0s1zS55ewZU89SqvqAUgYdXYPjPy2i13rWEbr0+rmD/bDT9/G70ue0C7Y2srsoyYNz89B1y4pqr1O3bqkOHZ4z+m4/Dk6GHyQUCL+kOU00aHzGbyedFw7OBcPvP55h8dDg5Ql7+1G1y4p+NHFvbH205pOSx8v7N1Vsc1mlkuGy6K65L0qdElNQmqyu8PjoccqqajB/LWfobap7fTrzE7D/GsHKtanp/t+7yIdczkA9nAIwrNsDy5/jh4mGSNhRP8hhwY6h1tOYOaKzvMcjFBLsGUmKZeeLKpKxwKg+lylYaHSqnpMfWZLp8fTT7Zi1+L/0m7Eiy8Ct9yiq72kTen9CLVy+khOOBXIsiR7CcTI9ZtzPkgIO/IYBOfHGJ6fgwdeNzjPIQylpY9mlkv6/BLmr600Xf+cf+5QLXvv6p1hl2eGzot5evWD2LtokmbgMWR+CXw+PwMPi3HCaezh8ufo47AL6WZ2yCTibJkW2FJVr3ueg5ZwSx/NLJfUm0VV6Vhajhw7iS1V9RgzoEeHx+V5MUWD8nTV12/OawCAbib2W+F4uTZOOI09XP4cfQw+SJdIhkzs/kMuqajBvf/caflxg+9Ezdy9iriTLd1zqGPw8fnnQEEBijSeN/nHj2Jn7oAOjx0+dtLQe8Txcn3kniitHYw54VQc9kZFH4ddSFOkQyZ2/iHLbT9yXDt/hVHBd6Jm7l7F3Ml+28sgZyAtKFAt3W/Oa+g357VOgYdM73vEdOH6yT1RADotEZf/P29yAXuMBGJvVPQx+CBVVox92vWHbCqfhQ7hcoWYyS9yuKUNZq4nLgA5mam6yv666Hxdu8qW7j7UPryiRs97xPFy4+QVWl5Px/Pr9aRzYqMNrMwXROFx2IVUWTFkYle3spF8Fnop3YnqyS8S/JySihrMXLHdcGAkH+vBKYW475WdYXNDXL1rM5a+ulDzWGN+/iwOeHoi15OO+1vaLHuP7B5mcyq7djCmzoz+PZNxDD5IlRVDJnb9IUcyjHNGWjKG53dD+f5GNLScaH88JzMVD0wpDHsnqpZfJHieg94emS6pbqQmJ3UIMIKP5XZ3XGqrNzdHaA9HbWMrZq7Yjv/5bj6e3lQd8XvE8XLz5BVaZD+9f89kDoMPUmXVkEkkf8hmV0zobftLtw+H2+VC6Z5DqPqmBVv21OPwsZPYsOsbAB2TkNW3nMADr1fC7YZiAKJ196q3R+aZH1+CkWd3VzxWUWEult00BEWDe2seS7r6Goy+9O6w9corjtZ+WoMnbxqKB16P7MuW4+UUL9gbFT0MPkiVlUMmZv6QI1kxoZW2Wm776HN6IMntQnPbSTz5XlWn1xn6f3nSpNJYvNbda23jcdV2yw4dbVM+1q23Ai++qLlq5bxfrcaJ5FTcOf5c1LzzhWI5eSikW2YqNs8ZF9GXLVdvUDxhb1R0MPggVVYPmRj5Q1bKMKh18Zetr6xV3S9Dwum2G5mcaiQ3Sbgsqw+8/rmOWhR6BnTm2ggeWnEBeO6jal3Pq2tujfjLNh7Hy5mvhMhaDD5Ikx1jn0YTk4VeHIb17YYF69Szh3brkoIJBV4Axien6pk0Ga7XRo9OPQPffAP07Kn5vEfH3ITHx94Utq1qQVgwq4ZC4mm8nPlKiKzH4IN0ET32aWTFROPxE50uDjmZKWhoUb/gBifNMjv5Uel5Sr02es2bXICkJH0r4V/d/h/MXlWuWa5rRgoaj58UNhQS+pnJ6ZKKXbVN+KiqHgcOH8cto/ohNTm2V/tH2vtGROEx+CDdRI596g0G1lfW4rkP93a6OGgFHqH1mL3jD/e8SPKL5GSmoOx/rwIW6Sj87Z6QPavqdR37tjH98Ng7XwodCpE/M8VvVOKZD6oRnNrjoTc+x/RL8zH3GvXEZ1YwM2xiZlsADs8Q6cPgg2KS3mDglfKDESURO9TcBp9f0pwkGUqtp8BMfpGR+3Zg1cr7tAu+/TYwYUKHh/RO8Jw1bgDO82YJHwopfqMST23qPOfEL6H98WgGIGaHTYzmK+HwDJF+LkmSYirNoJEteSk+hLtbBICxizaoXlC76Rha0UO+QADQNVSitaX2q+UHdA2DAPpzc0Djz1QeHgDC92oEt1Xk3fmJU36cf/+bUEtm6nYBux64OipDMJFsi673fXz8xiFIS3Zz+3VKeEau37E94Epxr6SiBmMXbcDUZ7Zg9qpyTH1mC8Yu2oD1lbXtAYGS7w8505I2yOP3APA/383XLK+V8lpPr83eRZP0BR6SpBl4AMbSc8tDIVOGnIlR/btHdVjgpdK9qoEHEOgBeal0r+V1R5rmXW/vW4/MNKaTJzKIwy5kG6W70pqgyXz/8938TnMFXAAmDuoFrydDVz05makdspSGkg89d/VOzQtleoobU4bkIjMlGR/uPoRDR9s69R4M69st7ITX3777DP7741c12/vWa6X4T3ZP5GSmwltVr7tnoqgwF+PO74WXSvfiq4Zj6JvTxfZJnV81HDNdTquHRuv3kaZ51zucBRfiJp282jm1oseMc2JIxuCDbKE1KVNCIBg4HGaJqATgtZ1f47WdX2vW43YBC64diLqmVs38GuHqCtV60o9lG6uxbGPHOQzBQzcL1lV2CDz0Dq0MWfBWYEnsB/UATk8i1TtvINycgz9vrrZ1zkHfnC6mymnNn9AzvyLSNO9685UcOtoWUT2xQu2cAoh4PgvnxFAwzvkgW5RW1WPqM1uE1OVCYKXHsx/ujWodwX9Iyb5T2P2H6zSf9/UZORgx80Vdx1cb6olkbkM0mZnzofVa5D1otF6r3s/YyukjVXsktC6aVtVjJ7VzrvTWGflsxernk6xl5PrNng+yhd4U41Z5tfxgVI8vf6lWLv4BupzUvhM+71er0Zacauj4ShlVzSwJDX5uNLvBU5PdmH5pftjVLrLpl+a3Bx56XsszH3QOPIJ/L79Wq9K8a+W4cXo6eT1zY8LRm+k3ks8nxS8GH2QLtTkYVpMQ2BAuKz0Jza2+qNRhdkdZI4LnDQQHDYea20zNORDVDS4vow2du+N2oVOeDz3zNNT6akNfq1Vp3tVy3Dg9nbyZpeEyPfNZIp17Q/GJwQfZIueMNOF1DjurG97/4pBlx+t9pBabn/pvzXL/KLwCv554lyV11jW3mk7bHjznQHTmzrnXFOBXV56vORnWqnkR8nFEpXl3cjp5K8652jEinXtD8YnBB9nCmy1+O/VLB3zHkuBDRC+HYt2HjuGxd74wlVhNXjpqVzd4arIbP730bF1tjFTwcURtDeDU7detOOdqx9B7fKvee3IGBh9kC3mcXO3uvVuXFF0rULTIY+63jOqHP2+u1p3FNJSdQQcAeLPTsHLrPsNtD51zEMvd4HrmT7hcUJzAqjS/QtTWAE7cft1odt9geuazOH1ODEUHk4yRLeRxchdOj4vL5MeKrx+EZdOGomuXFNP1BI+5pya725cN6r0X/dGnb+lKCPaLKfei35zXohZ4uABMHX4WapuM75ALdJxzEMvd4PLnAgj/uQAC80SUPjdAbM+viEV6zrna77TOt57j8z1LPAw+KOp8fgmlVfV4tfwASqvq2zM96snKWVSYi09+OwF3jT8XXTOMByGhGT6V6gz93pMDjkUlf1I9vhxwbB8xHsumDcWyaUOR6zHefexyAV0zwndE5n77Gvr1yDR83HAZTmO9G1zrczH3mgLd2VxJH7VzLn+uIznfRjLwUmJgng+KqnCTI3MyU/DglEJcc2EeAP3LPYPL9chMA1xAXVMrDh09gSPHT8AFYER+d7hdLhxq6Zx5NNyxahuPo6HlBLp2ScWRYyfw0+/21/W6PthVB3eSK2yG0/ZjN7Wi4WgbGlpO4Mn3qzSP+df/HgG3y9X+vJzMVHg9Ge3H1ptP4v6JF6BHVpri6/f5Jc19c7yedGyeM87Wu9FIM5ySccxwSpEwcv1m8EFRo7SiQvaz74rZTl1JSUUN5q+txOKn7sbofTu0n/Dll8A55xiuR+8GZT8d0w/3Tx6o+HsrgwYjG9EREenBjeXIdlrp04HAdupv7KgR1qZgJRU1KBqUhy2/Ga8deMibu5kIPAD9wxdryg+obj5m5dg5u8GJyE5c7UJRoTdx0f2vVuCqQoGZDY8fB7p0QZGOoidO+izZlG14fo7m5nYA0NByUnOFiZX5JJy6NJSInI/BB0WF3pUS9S0nxCzpdOm7oJ7z61dwKinwZ9Ht4XdQfP2giHsBktwuXDckT9feMnrOm5VBgxOXhhKR8zH4SFDRnvhlZKVEVJd06gw6wi2RPXzspGXZPicUeHUFH3rPG4MGInIyBh8JSMSeHoGhhpQOW8sr2XuoxZI6233xBXDeeZrFVl54JeZe/UvNclZk+9RKqsZES+q4SoIovnC1S4IRubX1GzsO4hcrtmuW82an4cN7r4j8YqKzl+PDL77BzX/5l6FDW7EdeqytMHHKBV3UBnhEFBkj12/2fCQQM3t6GLlAnTjlx0ule1Fd3wIXgIv6dMOo/ByUVjeotqu2qQ1b9tSr5rhQZSDoGNm/O0YC6NolBUcMpG6vbWpFaVV9RBfqWNp8zCkXdNEb4FHicErwHa/Y85FA9Capku/yjVygit+o7LRluhFdM1Jw5HjnYEDxgvjXvwLTpmked+qND6O074Wn6+mSgoXXDwIA/PzbXgg9QoeQIrlQ2/2lJ7L3KxJyXhOtoSq7k6GR8zgl+HYaJhmjsPQmu3r8xiFIS3brvkAVv1GJpzZVW9rW0Drb64tgAmmwZdOGwu8HZq5QToKm1SYg8gu16EDESRd0o8EykR5OCb6diEnGKCy9Kyl6ZKapDs8AgeEZn1/CiVN+PPNB9AIPuc6iQXm6Ag+fz4+RD72jWW7+2s/gyUgxFXjIbQJOnwczSipqMHbRBkx9ZgtmryrH1Ge2YOyiDSipiF7iNSM72totljfAI2fSGnoGIvubJv0YfCQQecWF0iXchUDXI1zQfYF6qXSv6aEWLY+vfUTXjrKorW3PQirvqaKltqkNpXsORdS+SC7U8t1X6HmW5zJEKwBx0gU91jfAI+dxUvAd7zjhNIHI6blnLC+DC+FXXMybXIBDR9t0Ha+uuRVfNRyzupnawYYszIihkYumVQOORi/UZib+WsVJF3Q5WNbay4bLk0kvJwXf8Y49HwlGz54eRi5QfXO6WNKuzLZj+no5Lrnk9F4rCm3Sq2uXVNWeIL2MXqjtvPvS2/sVCxd0K/eyIQKcFXzHO/Z8JCCt9NxG7jiH9e2Gh9743NTQiwtAtc5ejtEPvo0P5o7XvNAMz8+BJyMFjWFWzoTqcUaqYk+QHmbvvO28+9Lb+xUrF/RYWp5MzsfetNjB4CNBqaXnVrtA4dv/33hJHwBAarIb0y/NN7zaRe/QSr85rwVWu0wp1HVBTHK7cPuYfDz6zheaZb2eDIzq3z3sxU0PCcA1hYEgzsgqFbvvvpx2QecGeGQVpwXf8YxLbUlRuLXwwYLXxavl+ejaJQUAcOaez/H6C3dq1vvYmKl4bOzNnerQy+eXMOzB9apJxHJDlpOeOOXHyOJ3dKWDBwC3Cx1eq5F2ystdte6+or3c1e58I0R2YZ6P6GCeD7KMzy9hyYbdYXsSQtfFh8twmts1A6PO6aGrrtLdh8xlOA3T5tmrtuO1HcorRn723XzMvabgdN06c0pcXejFmxW1nR43miNAKdW6bBlzDRBFFYNv6zG9Ollq1bZ9YR8PXZmRmuzGTy89G0DgDzspSed85m/j31ERtFH+IllfWYs12w/gsEbq9LWf1uCeogvav2z0zq8oraoP+7jRVSry0Me9q3d26qGRe4qIKHq4M7S9uNqFVOldmfHo+i9QWlUP/wsvAi6XduCxcaPqqhWZzy+htKoer5YfQGlVfdjkP8HJup79cK9m4AF0Xk2id35FuBTwMjOrVBrDtLXx2MmIcn3oOWdERHZizwep0tsj8Oui83WVK9l5UPdwgp5xWaVUyXoEvzY9s+A9CvvPqB1XSbRyfXAsm4icgD0fpEq1R0CS9OXmQGDVSv6c13SnLtaTAVTtAq5H8GvTk1PitjH9DB9XSTRyfdiVNZWIyCj2fJCqcD0C92x8Hr/Y8g/N5144exWa0s9o/3/wBVVtrFVvr0BWWorh5bGA8lp+rSWoEwq8WLVtvyU5AqzO9WFn1lQiIqMYfJCq4HXxRnJzqNG6oOrtFfioyvzeLEpr+bVySliVI8DqXB9GelI4yY6I7Mbgg9QdPYqiQXnQSiG2YnAR7iuapeuQWhdUvXf7z5fu1VUumJ75D2qz4K1K0GV1psVE2LOCSyOJ4geDDwpv0CCgokKzWL971una6h7Qf0HVe7ff0ubTVU521/gBmDVuQMQXLCsyblqdaTHSnpRYv7BzIi1RfGHwEWOMXgQiKZ/TJRW7apuw79udaYf06YYfXNxHVztHPfwOak2kIx+Rn4NXyv6DI8dPwpORgk//cwQSgPzumbhpRF+U7z+C2qZWdM1IxpHjpwwdX0lqkguTL8zDWd0zdadC1zqvenMEhB5nWN9u+OSrw+3/f/KmoXjg9cjTnA/Pz4E3Ow21TeF3JFYK/AJJ5L7Ecx/u7bCSJyczFdcNycOEAm9UAhEjn1ulFU3yRFqtxG5a70GsBVpEicDyDKfFxcVYvXo1du3ahYyMDIwePRqLFi3Ceeedp+v5iZzh1OjdnRXlAaDv4YPY+PT/aLbvpz+4H++eMwK5nnRcOzgXT2+qNr3SxE5ad8xW3WWHO064tOz3T7wA3TLTIroYllTUhE1YBihnX1V7TjCrexiMnF85Fb3SfBatVPR63wP2oBBFztb06kVFRbjxxhtxySWX4NSpU/jNb36DnTt3orKyEpmZmZrPT9TgQ+nuTu3CEWn57Y9PRbfWZs22hU4glYcJUpPdOHHKr/n8WORC+FToRs+rEr35R4we10xdXbukYOH1g3R9ftTaGUkbtepVOg96096vnD6yU0+UyPeAiIxdvy3P81FSUoKf/OQnGDhwIAYPHoznnnsO+/btwyeffGJ1VXFDa5kkgA75MXx+CfPXfmaofPDx5dwcWoFHvzmvhV25Ih/HqYGHLDTniNH3QYmR/CNGjmu2royUJEwo8JpqXzCzbdRTr9J5MDuRVuR7QETGRT3JWGNjIwAgJyf8JMO2tjY0NTV1+Ek0RhNOLdmwW3FsP1z5rdUN8Hz5ua6EYGN//hfFoCOehEviZVXiL63jmD2u2bqMvk6r26i33nB1mJ1IK/I9ICLjojrhVJIk3H333Rg7diwKCwvDlikuLsaCBQui2YyYZ+TurqSiJuwOs4rHvegijCovR4lG2XgPNpQEn3urlquaXc5q5nlm2hzJclsRzzWa9j7cRFqR7wERGRfVno9Zs2Zhx44dWLlypWKZuXPnorGxsf1n//790WxSTNJ7d9cjMw0L1lVqF/w27fmUi3oD5eWKxR4bMzUhejnUBJ97qxJ/6T2OFc8z02az7RP1XKNp78MtSRb5HhCRcVHr+bjjjjuwdu1abNq0Cb1791Ysl5aWhrS0tGg1wxH03t3BBdWu5Ev2V+DvK+7VrO+cX7+CU0mJvco63B2zVYm/tI5j9rhm6jLzOq1uYyRtBcwldhP5HhCRcZb3fEiShFmzZmH16tXYsGED8vPzra4i7ui9uzt0NPw8j03Lfoq9iyZpBh5yL0eiBx6y0Dtms3fZodSOE8pMQjG9dSkd20j7rGhjJG2VFRXmYvOccVg5fSQev3EIVk4fic1zximuThH5HhCRcZYHHzNnzsTy5cuxYsUKZGVloba2FrW1tTh+/LjVVcUV+e7O6+nY7ev1pLcvAQzuEk72nWqfQHpW49fKB962DT6fH6MefseytnbrkgJA34VLhK4ZKfjrf4/A9Ev7Qc+1IzfonIYqKszFkzddhG6ZKR0e96o8Jxyl9zO0fUaPa6QutWMrPSczNQlnpCVZ3sZI2iqTE7tNGXImRvXvrhkoiHwPiMgYy/N8uBRSbT/33HP4yU9+ovn8RM3zIVPL/OjzS7hz+h/wp2fv0T5Q0Nv64ZeHcPNf/qX5lBmXnY30lCSs3Lov7GqarhkpuG1MP8waNwDrK2vDJiwL9f0huUhPSUbFwUZkp6dg7IAe6HlGmmqG09PZV5ux//AxHGs7hX+UHVBMQx584Thxyo+XSveiur4FkIDs9BS4XIFcFz2y0uHN1s6mGfq6cjJT8eCUQlxzofGLk8jsmmZSpId7DoCop1oXmc6dGU6JxLA1yVikEj34UDRiBLB1q2qRlYOvQrflz3XOYvnPnR1SZyt5/MYhmDLkTLyx4yB+sWJ7p9+HXuxPnPJjZPG7aGg5EfZ4WtknjRCxt4dVCcaIiBKRkes3B/9jWWMj0LWrZrGL7vgr0nN7dboQG81iWf3NUfj8Eh54/fOwv5cQuBAvWFeJCQVefPLVYcXAQy4fuo272TteKzZzU6OVACv4dfMumYgoMgw+YlFpKTB6tGoRqV8/bHnnY9Q1t+L/wlyIzWSxfOzd3aj65qjuRFBG8zZE2nuhdzM3M4wkwIpWG4iIEgWDj1jy5z8D06erl1mzBrjuOrgAjFIpZiaLJQCs21Grq9yHu7+B3imnPbPSI96ZNJTVcwasSjBGRETaGHzY7ehRYOpU4DWNRF/HjgEZGboPG+2L5JL3qjTLyHM+hvXthsseec+yIY1ozP+wKsEYERFpi/reLqTg448BlwvIylIOPJYsCaxakSRDgQdg/0UyOHfCJ18dtmTPFOD0PJbQ49V824NSUlFjqr1yUiql0MeFQIDDJFRERJFj8CGSJAELFwaCjksuCV9m2DDg668DZWfONF2V1sU02oJzJ1g1pKE1j0UCMHf1TlM7k1qVYIyIiLQx+BChvh4YNQpwu4G5c8OX+d3vAL8/0CPSs2fEVRrNYhmOmevsrO/175R90qohDT3zWA4fO4klG77U19gQkSTAIiIi/TjnI5refRcYP169TGkpMHKk7kMamWgpX0zvXb0TR45p5/kI5ZeAW0aeBZfLhaZjJ/DKp3qGNFyoaw4MochtG9a3G9yuwPGUuF3AsL7dVI+stwfl2c3VmDVugKleCjNLekUmzHIKnhMiUsPgw2o+H3DPPcDixcplrroKePllwGASNTPZNycUeDF/7WeG6gn20pZ9hsoveW93+7/lSaCejFTVwAMIBCaffHVYdRmr3h6UxtZTWLJhN2aPH6CrfCgjS3pFJD9zGp4TItLCYRer7N8PnHMOkJysHHj83/8F5nKUlCgGHj6/hNKqeqwp+w/+8sEerNl+AKVV9Xhjx8GwEy0bWk7gFyvKUPxGZdhjPf9hddhU6SLIy2jfqdS3fFerZ2N4fg66ZqSolpE9+s4Xpief6qU0+bU2wsmvTsZzQkR6sOcjUv/4B3DDDcq/z8oCtmwBCgo0DxXujlHmdkE1YdhTm6oxuHdXXHNhnuaxRJGX0a4pP6CrvFbPRpLbhdvG5OPRd77QdbxoZiRlRtTOeE6ISC/2fJjR1gb8+MeBVStKgce0aUBrK9DUpDvwCHfHKNOzgOO3r1bA55c0jyWSBKCh5SRyMlMtWcY6a9w56NpFX++H3uW7ZhjJiJooeE6ISC8GH0bs2hXYayU9HXjppfBl/va3wNDKSy8BaWm6DmsmFXo4DS0nsWVPvSXHstp1QwI9MpEuY01yu7Dw+kG6641GsjWfX/o2w6s99ccqZoklIr0YfOixbFmgl+OCCwKbvYXKzwf27g0EHT/8oeHDm02FHk5pVX1M9HiEmlDgtWwZa1FhLu7SOZnU6mRrJRU1GLtog64Mr9GoP5YxSywR6cU5H0qam4Ef/Qh4803lMnfdBTzyCJCUFFFV1t4J6u/z8GanobntFFrafBbW35GcYl1eamnVzrSzxg3Ayq37UdsU/twF12sVI7sER6P+WCcntqttbA17jhLxnBBReOz5CPWvfwV6ObKzlQOPt98O9HIsXhxx4AFYdyeY60nHqLN76Cp7/8QL8OG9V+CRH1xoSd3hhBtSkZexThlyJkb172564mGS24X51xbABTEZSY0MjSVqRlRmiSUivRh8AIFA4sEHA0GHUsKvESOAb74JlJ0wwdLq5TvGSLgQ+GIf2b+7rmP95/BxbK1uwPgCLyYp5AhR061LSqeJn6HXlGhnBhWZkdTI0FgiZ0Rlllgi0sMlSVJMzU1samqCx+NBY2Mjsg0m4TLsm2+Aa64JpDRX8tBDgZTorujerenp0ncBuOKC7+Ddz7/pUM7tAqZfmo+51wTuOt/YcRC/WLFdV71qmUdzPem48ZKz0K9HF/TITANcwKGjbe3DJQA6DKEM69sNn3x1WHhWSxHZNF8tP4DZq8o1y8363jm4a8K5CX93zwynRInHyPU7Med8vP12IMuomq1blTd/iwL5jlEpN0euJx3XDs7F05uqOwUokgQ8vakaF53VDUWFueiWqW+VDaAceNw1foCuFOWhmUD1Zga1kpGMpGbpHRobc04PXmQh5j0hIudKrOBjyRLgjjuUfz9xIrByZSAxmA2C9xWpbTyOhpYTyDkjDd7sQK/CZY+8pyuBU6QTWF0AVm3bj1njzKUnj0ecTEla2NtDpF/iBB87dyoHHk8/DUyfLrY9CpTuGLWW0AYncIp0AmvwsXj3GiBPppyxvAwudFxTxMmUxP1siIxJnAmnfn/HlSndugGffx4Ys4iRwEONkQRO8l16pJdBJoPqiJMpKRzuZ0NkXOL0fAweHJjH8fnnwH/9l+7so7HCSAIntbv0aNSpJB67oYOHxuLpdZE53M+GyJzECT4AYOjQwI8DGZ1zoDWBVY0V8xfiuRuakylJZmQ/G35miE5LnGEXhzOTwKmoMBeb54zDyukjcfuYfmGfG8qK+QvshqZEwf1siMxJmODD55dQWlWPV8sPoLSqHj4928QKqkPv88zMOZDv0v938kAsC/NcqxODnTjlx31rdip2QwOBbuhonH+9RHwWKDFwPxsicxJi2EXEEIDZOow+L5I5B+Gea2VisJKKGty3pgINLScVy9jdDR3Pw0EkHpdgE5kT9xlOlTKHypdXK1YpmK1DRNtEMbLpGgA8fuMQTBlyZlTbFCqezjfFDvlzBYRfgs3PFSUKI9fvuB520ZqJDkQ+BGC2DhFtE8XIpmsy0d3Q8XS+KbZwCTaRcXE97CJiJrrZOuJplryRTdfs6oaOp/NNsYdLsImMievgQ8RMdLN1xNMseaNttCMTaDydb4pNXIJNpF9cD7uImIluto54miWvt405mSm2dUPH0/kmInK6uA4+tNKMuxBY6RDJEIDZOkS0TRQ96dy7Z6Ziy9zxto1/x9P5JiJyurgOPswk5hJVh4i2iaL1WlwAHvp+IVKT7fu4xdP5JiJyurgOPgAxM9HN1hFPs+Sd8Fqc0EYiokQQ93k+ZCI2OTNbRzxtwOaE1+KENhIROY2R63fCBB9EREQUPUwyRkRERDGLwQcREREJxeCDiIiIhGLwQUREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiISKtnuBoSSE642NTXZ3BIiIiLSS75u60mcHnPBR3NzMwCgT58+NreEiIiIjGpubobH41EtE3N7u/j9fhw8eBBZWVlwubjZl9WamprQp08f7N+/n3vnCMZzbw+ed/vw3NvDrvMuSRKam5uRl5cHt1t9VkfM9Xy43W707t3b7mbEvezsbH4Z2ITn3h487/bhubeHHeddq8dDxgmnREREJBSDDyIiIhKKwUeCSUtLw7x585CWlmZ3UxIOz709eN7tw3NvDyec95ibcEpERETxjT0fREREJBSDDyIiIhKKwQcREREJxeCDiIiIhGLwEac2bdqEyZMnIy8vDy6XC6+88kqH30uShPnz5yMvLw8ZGRm4/PLL8dlnn9nT2DhSXFyMSy65BFlZWejZsyeuu+46/Pvf/+5Qhuc+OpYuXYoLL7ywPbHSqFGj8Oabb7b/nuddjOLiYrhcLtx5553tj/HcW2/+/PlwuVwdfrxeb/vvY/2cM/iIUy0tLRg8eDCWLFkS9ve///3vsXjxYixZsgTbtm2D1+vFhAkT2vfWIXM2btyImTNnYsuWLVi/fj1OnTqFK6+8Ei0tLe1leO6jo3fv3li4cCE+/vhjfPzxxxg3bhymTJnS/oXL8x5927Ztw9NPP40LL7yww+M899ExcOBA1NTUtP/s3Lmz/Xcxf84linsApDVr1rT/3+/3S16vV1q4cGH7Y62trZLH45GWLVtmQwvjV11dnQRA2rhxoyRJPPeidevWTfrzn//M8y5Ac3OzNGDAAGn9+vXSZZddJs2ePVuSJH7mo2XevHnS4MGDw/7OCeecPR8JqLq6GrW1tbjyyivbH0tLS8Nll12Gjz76yMaWxZ/GxkYAQE5ODgCee1F8Ph9WrVqFlpYWjBo1iuddgJkzZ2LixIkYP358h8d57qPnyy+/RF5eHvLz83HjjTdiz549AJxxzmNuYzmKvtraWgBAr169Ojzeq1cvfPXVV3Y0KS5JkoS7774bY8eORWFhIQCe+2jbuXMnRo0ahdbWVpxxxhlYs2YNCgoK2r9wed6jY9WqVSgrK8O2bds6/Y6f+egYMWIEXnzxRZx77rn4+uuv8eCDD2L06NH47LPPHHHOGXwkMJfL1eH/kiR1eozMmzVrFnbs2IHNmzd3+h3PfXScd955KC8vx5EjR/DPf/4Tt956KzZu3Nj+e5536+3fvx+zZ8/G22+/jfT0dMVyPPfWuvrqq9v/PWjQIIwaNQr9+/fHCy+8gJEjRwKI7XPOYZcEJM+IlqNjWV1dXadImcy54447sHbtWrz33nvo3bt3++M899GVmpqKc845BxdffDGKi4sxePBgPP744zzvUfTJJ5+grq4Ow4YNQ3JyMpKTk7Fx40Y88cQTSE5Obj+/PPfRlZmZiUGDBuHLL790xOedwUcCys/Ph9frxfr169sfO3HiBDZu3IjRo0fb2DLnkyQJs2bNwurVq7Fhwwbk5+d3+D3PvViSJKGtrY3nPYquuOIK7Ny5E+Xl5e0/F198MW6++WaUl5fj7LPP5rkXoK2tDZ9//jlyc3Od8Xm3b64rRVNzc7O0fft2afv27RIAafHixdL27dulr776SpIkSVq4cKHk8Xik1atXSzt37pSmTp0q5ebmSk1NTTa33NlmzJgheTwe6f3335dqamraf44dO9Zehuc+OubOnStt2rRJqq6ulnbs2CHdd999ktvtlt5++21JknjeRQpe7SJJPPfR8Ktf/Up6//33pT179khbtmyRJk2aJGVlZUl79+6VJCn2zzmDjzj13nvvSQA6/dx6662SJAWWYs2bN0/yer1SWlqa9N3vflfauXOnvY2OA+HOOQDpueeeay/Dcx8dt99+u9S3b18pNTVV+s53viNdccUV7YGHJPG8ixQafPDcW+9HP/qRlJubK6WkpEh5eXnS9ddfL3322Wftv4/1c+6SJEmyp8+FiIiIEhHnfBAREZFQDD6IiIhIKAYfREREJBSDDyIiIhKKwQcREREJxeCDiIiIhGLwQUREREIx+CAiIiKhGHwQERGRUAw+iIiISCgGH0RERCQUgw8iIiIS6v8DtlpHsLlV3DcAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.scatter(\"total_bill\",\"tip\",data=data)\n",
    "plt.plot(x_test,y_pred, color='red', linewidth=2, label='Linear regression line')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "b3831c20",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn .metrics import mean_absolute_error ,mean_squared_error ,r2_score "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "2843b67d",
   "metadata": {},
   "outputs": [],
   "source": [
    "s=r2_score(y_test,y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "4591513c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.5449381659234664"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "s"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b64088ff",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
